name: Win32 Build

on:
  push:
    branches:
      - main
      - x64-build

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    
    - name: Build app for release
      run: msbuild game.sln -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Copy scripts to build folder
      continue-on-error: true
      run: robocopy ./as/scripts ./build/scripts /E; if ($lastexitcode -lt 8) { $global:LASTEXITCODE = $null }

    - name: Archive build output
      uses: actions/upload-artifact@v4
      with:
        name: x64ReleaseBuild
        path: build

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        tag: nightly-${{ github.ref }}
        name: nightly-release-${{ github.event.repository.updated_at}}
        artifacts: "*.zip"
        draft: true