name: Windows Developer

on: 
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    
    - name: Build app for release+developer
      run: msbuild game.sln -t:rebuild -verbosity:diag -property:Configuration=Release+Developer

    - name: Copy scripts to build folder
      continue-on-error: true
      run: |
        robocopy ./scripts ./build/scripts /E; if ($lastexitcode -lt 8) { $global:LASTEXITCODE = $null }
        Compress-Archive -Path build/* -Destination q2as-developer-windows-x86_64.zip

    - name: Setup variables
      uses: actions/github-script@v7
      with:
        script: core.exportVariable('GITHUB_SHA_SHORT', context.sha.substring(0, 7))

    - name: Update release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release edit nightly -t "Nightly" -n "Latest nightly build" --latest
        gh release upload nightly q2as-developer-windows-x86_64.zip --clobber

    - name: Update tag
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.git.updateRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "tags/nightly",
            sha: context.sha,
            force: true
          })
